const data = {
  products: [
    {
      name: "Nike slim shirt",
      slug: "nike-slim-shirt",
      category: "shirt",
      images: "/images/p1.jpg",
      price: 120,
      countInstock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Addidas fit shit",
      slug: "addidas-fit-shit",
      category: "shirt",
      images: "/images/p2.jpg",
      price: 120,
      countInstock: 20,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "nike slim shirt",
      slug: "nike-slim-pant",
      category: "shirt",
      images: "/images/p3.jpg",
      price: 120,
      countInstock: 10,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "nike slim shirt",
      slug: "addidas-slim-pant",
      category: "shirt",
      images: "/images/p4.jpg",
      price: 120,
      countInstock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
  ],
};

export default data;
